name: Frontend - Build and Push Docker Image to Docker Hub

on:
  push:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to registry
        uses: docker/build-push-action@v4
        with:
          context: . # Ensure the context points to the Frontend directory
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/shangilia_website_old:latest
